import { Router } from "express";
import authRoutes from "./auth.routes";
import projectRoutes from "./project.routes";
import uploadRoutes from "./upload.routes";
import channelRoutes from "./channel.routes";
const router = Router();
router.use("/auth", authRoutes);
router.use("/api/projects", projectRoutes);
router.use("/api/uploads", uploadRoutes);
router.use("/api/projects/:projectId/channels", channelRoutes);
export default router;
